"""
This module provides functions to validate tokens in the token stream generated by the lexer. It checks if variables, integers, floats, function names, and operators are valid according to the language's syntax rules. The main function `checkTokenStream` iterates through the token stream and raises an exception if any invalid token is found.
"""


from dataReference.operators import operators

def validateVar(var):
    for char in var:
        if not (char.isalpha()):
            return False
    return True


def validateInt(integer):
    if type(integer) == int:
        return True
    else: 
        return False

def validateFloat(float):
    for x in str(float): 
        if not (x.isnumeric() or x == '.'): 
            return False
    return True

def validateFuncName(funcName):
    for char in funcName: 
        if not (char.isalpha()): 
            return False
    return True

def validateToken(token):  
    if token[1] == None:
        if token[0] in operators:
            return True
        else:
            return False
    else:
        if token[0] == "var":
            return validateVar(token[1])
        if token[0] == "int": 
            print(token[1])
            return validateInt(token[1]) 
        if token[0] == "float": 
            return validateFloat(token[1]) 
        

allowedTokens = operators

def checkTokenStream(tokenStream):
    for token in tokenStream:
        if not validateToken(token):
            raise Exception(f"Invalid token: {token}")

            
    